apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dev-nc-default-us-east-1.yaml
  - dev-np-base-spot-us-east-1.yaml
  - dev-np-elk-spot-od-us-east-1.yaml
  - dev-np-istio-spot-od-us-east-1.yaml
  - dev-np-monitoring-spot-od-us-east-1.yaml
labels:
  - pairs:
      kustomize.toolkit.fluxcd.io/prune: enabled
