# gitops-flux/infrastructures/dev/dev-eks-us-east-1/elk-logstash
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../infrastructures/base/elk-logstash
patches:
  - path: patch.yaml
    target:
      kind: HelmRelease
labels:
  - pairs:
      kustomize.toolkit.fluxcd.io/prune: enabled
