apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elk-logstash
  namespace: flux-system
spec:
  values:
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        memory: 1Gi
