---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-github-oauth
  namespace: monitoring
spec:
  encryptedData:
    client-id: AgBj74wfoQCpzUCad+z1TPM0snwR4+8lRumMurj3Sbd30YXNsND0Zwag9H0oSNynQ1UL1E4wxpF0jUyHdBJlqKyn1d3DvVvXHfnmO72x0D97fniEnQ3S73JTU6BxF0Cmk6Yt5jr+ugGIVyvnMB3GdyqlrerKhL0oqnCj5Ci/aui1soTp7qt0JoIV+9iF6AM2j9CpWfs8kYY2PFiqAjJIh5TLyAOx8qkjVig/MTkkiH4Bf2XQMw6SRzNzZ09Zrsx8SmtiOJRf+CLoHR0VwSj+0klzepAlddSYGUbbk1J4W7n8yPkyYq8+WgcCpOgxlqMV9T/R3Qa3+QS3rd5mmgqYrnU84EaBVYJeI0cvSf7zf0c6/alEM+Vn5Lfmsvr+bPyhkGBXzG/aIDzelBsho8pnJf6ar19jFZrcTf2D5FYqEKNLMiTMPr/al4x8bZwgu5eVWAjXTH1lZccW93qTNX+fKnNVK/eqI1zZ/mwfK2qDY/a+WRS4E298nB21ojMOvh29zrvbB57O4AGEc69e572B8M8EYKEU1ODk+iHWJIee11XaaiW6JfvOAympn6mFgTHk0WCoNz9UKz0s4ESWwjcB2x4J+BU09AbyEPuxqlmjYDc3jPWyU0cuDwK39iy+ZHBk48pLl/p7mw50opHucxKJMHEEG0Rzh6e4tTdeXLQIc61QozAlw0jcCqOO/9DApTshc6UWnRBN0X1PeFRpVA+4hsVPNUaxLg==
    client-secret: AgBIsYzQcIA9ih5XA3e90lFh9mJo4mCewIHtwyH/ponLoXNYwJ/oGKZziVyTwiGfOGqqG01fw/nJ/MpRl8rrvjStGga4l+pAj5+yribRxpzFtYh+Qw8kY3ju70kxSnDQjKPCM5JHzesQl1tg2vW38vlv6fuiXoUW+oKG65qg5ZnMvdlOhdsjszz2hZMNZkluhvmTfrydzAOy/g3i2qa9NUJWZxxZo9u4RUk5Sv5degnQi7ehA6xFX3793+HcKG6Ngp+6F8RcftVHCNxWu6Kxk3PNftwt8Rn9+X0o1GDTl2CRc1SuqxGD8ZHXQiHiDVpM4OOCKtA2bOjKR9d1hBuqxIa9j15tpuFDpva8yqXaLt73SN6C5S6kGCyABMH0cfaAfLC3gRFogFpKc+H0cN3e52wHP+nTTZHLNDwO/VNlGEZ3Ex0/ZtSiOHW9VgZ7OJOgD4W3XsaU/Z9x7w5vvjEk5ksPKRlTI8AZV5yWrhDIUzgNWaxmqfydyqyuC9UqyZnCNwG7pnhI9XbFYte6mUMZgEyITViakSbOhF7Kwbi0hcS47ytezxB30lGUWoUwUtLUMcksxVO4u4RN1LteiJSvUvah33+6Xy/7NvnF/aI15jvalkPrvn4umUf6cDMw8sjUGBXdODOfT0R/68WUsJYNegu+dEYqSjIf2DPk4hkES9TO2yW0oMZp8q/cAwSRAIWvs2Jqo3repcb+4Smw4DIc5WmG2lpLn5RvJskSRJRg/RoW/GJg780jTLAq
  template:
    metadata:
      name: grafana-github-oauth
      namespace: monitoring
