---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-github-oauth
  namespace: monitoring
spec:
  encryptedData:
    client_id: AgC7W1CposS7purickAxk1NOfgF0eZ9RAFDRjsK6O5ZHrQN3L4SpVjq2Eqb3cW+q44uAfialjA8GvILMUhnSkuOEkCfvQS2s1reM7PTDMUtdj5NxHjpbyXnDlHqrsGhQWtl3UHI7cLN8UokuiOF3K3JnXnPDtHx2UDgSA/xgFpwMryVs/KBgHflF8H85RF87/5xtuCz6ZygufA2i/zF6xfRc5I/NQQm5onqwtSuF1tjhMIr3QSdV6JB4Ahi8Sknx/w+Z3a1b4y8k/qa97/qIqDj5lZeNb5LNTuNAvciQIbCfTthXponivdOsChX4kNZmL44Vt9TbzWMR7/gG7PddjPjeQQhvWkz1+mmExehaTbvZctM4tUosAzPh6xEVy3D16CjtwX4+OoMdS2uHu+bTmikd1H5Ndxd48bz4LganoBq99E2mcy8yZH1qtoNma5GVCZCEaL3q8FVD6MCka3l9XEiy6HheCgSy2n8ak31w3MRptdQQjybP+iW8MhBA4Po2Fn4sPzVdZy2zNw9fM9DCBFlz0PqolOnmy0Yf34KELuGGY437VBs/VMY9eog1WMrrfX/yJsyhydpjmO6QWGkfk+mWmnfl2OLfkuEuK7g5X3eMiCA12s5hIin02sjwNuhkWCc67LxqrysVukfTOPWKMVkNO6B24st26sjdPh39xxsFWfDW3RjvacmYGBwXADVRGUqfBs5Qkoj+Vwa0VVeNqAdCLGA2HA==
    client_secret: AgBcrZF8UnffQQfbgZM5seTtSiiw7WKR1opAawvRvbyLSBUaIR43RaeeSdL6raFbhpCjGVrBed+W9PGPiitxjv+yxtf3/UFmGqzmXM1xMt09E13vnYg0j/Qyb5q1mlOEoqsLa+06SMiFM/jRZYD3G3vBB4cRMdiWFjuORShFxn/Nn8f0GuhiNI1nCkkGVyXPXzb0BE7B4MYEsMgJLWSfaP+EkTTqXq9GOctYIGhG02pZYs/4zLguzCD1/EgbXIHGvTYfbE5ReRu93uB6clvJ2vjPtwCrpO1kk5Mankagw6MvLKVWzsaoTEVZQotKqYvaZ3GireeI4+Du3B6B0806bvPIgVDt2dtoSckMPhv5EzpJC9yIEoq8SySOFRyHxQxX4wwwpf+4NPfgfOCsglDbTTFCXsyo1RKgk4CDkJrOhFKxI3gFLUEVefZQlnnRQCRKyF2VZIE8pg3Q6Vv9/uUjsZqbv/Lff09OgoF/jqmdInsSyyeFkn5cW4GkoK2/P5Hnl+cqxJFm1jnTYdElXhXgMKc0anqq5xTH1DtFbtRNkV9qUTuZAep4YhLMpK1u6m1ZBugdun5nM6CPrYYKKujaGoNztsxJn8LYZKvyS9uulz7Ykh5lQ0YXQwN0MLKSzumyO415LIrpCUzZgQKjzTD6mkPMDuzQSF+46ME2HUsfn/Qg1F3aP2Fw6W0M9lITFh+XdELsVU5NrE0sWHG4MuhqrlRbMCt6FL+q2mCYIPM5nTplRxY818Be8YXb
  template:
    metadata:
      name: grafana-github-oauth
      namespace: monitoring
