apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  timeout: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "72.6.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 20h0m0s
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  targetNamespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-irsa
      valuesKey: values.yaml
  values:
    prometheus:
      prometheusSpec:
        retention: 15d
        thanos:
          objectStorageConfig:
            existingSecret:
              name: thanos-objstore-secret
              key: objstore.yml
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
    grafana:
      persistence:
        enabled: true
        size: 5Gi
        accessModes:
          - ReadWriteOnce
      sidecar:
        dashboards:
          enabled: true
          searchNamespace: ALL
      envFromSecret: grafana-authentik-oauth
      grafana.ini:
        server:
          root_url: https://grafana.25c-team1.art
        auth.generic_oauth:
          enabled: true
          name: Authentik
          allow_sign_up: true
          client_id: ${authentik_client_id}
          client_secret: ${authentik_client_secret}
          scopes: openid profile email
          auth_url: https://auth.25c-team1.art/application/o/authorize/
          token_url: https://auth.25c-team1.art/application/o/token/
          api_url: https://auth.25c-team1.art/application/o/userinfo/
          role_attribute_path: contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-editor') && 'Editor' || 'Viewer'
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true