# Role ARN for the Karpenter service account. Regenerate: see cert-manager/sealedsecret.yaml.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: karpenter-irsa
  namespace: flux-system
spec:
  encryptedData:
    values.yaml: AgALog88OON5FOsq+ylow2knf2bg3ZA/VFep1hoCyIWFOPRhKe6aiZ5lWtZjBiPjdQ751aA+6C7FVvF0hDk3++bBDtqZWhGIO2XUDM39ksLmuhk6D7ZP/Pf6J/i11YewvYVivowSUj5xsp7y6FjIoU8ta5/NyKm2t8dm8Zpo/GaRBWV94+1UEuk50cjGO7j63PBjYg3rUVt3M34LsWkpbr7zguhlKe6XrCvDoTRColDGEzsHMNU5KRr99cI/HgezR00hzAmuvbha2Kj4xnKA33ffi6laIArbYOkpoeN3+dJGRFTtSox9pjoji8aiP/z7RxAOoOX8fRCQY5eb/qf0GLOPBt1Xh636Wxyj04GYSqS03oycVmhiph9gDNjF5yTYgyBXvmaUrbeJDU9DihDfF2Sjx86q5atkZied5PyuvKmSzWuaafB/IwlpRZDWoAw6d/z7fxFMkm9R1h4q/G/HAqngIR+0qvfOh9g7sn6/zXojc35t4+OuzR1FdHFaFW6BR9VXDKU8wCft2DRU9/RGfrYC3uVILuhC8hutErrBFSnpsmVDpNQ6f4LRb3j8padyrfLhiwFsMHcipQPFFleFPBracgOACD2/RC+s3OCe1k374Z0JzXx/FVcdP98MaZm3sZSnT+/vxsNQVJXz+i/Tske5hCDw+HDROxKtFMmcAXPhBDPdmd9rOgwo6smxzMq56XX0GlUHBWIYSzbqux3V/itcOuQ2UfwgwwnuORXczyTLQDB8lSXpROEWggjxVVTU1bOtWcJ1upC/vYsfwcx2pudmFh7PL5B9S0gNowKAn4ORSU/T2pSbPashcv9vOqXIYKxoutlvlY1S7IWONTl29cHldD6bKxeEdwpACxk=
  template:
    metadata:
      name: karpenter-irsa
      namespace: flux-system
