apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-secret
  namespace: monitoring
type: Opaque
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: u25c-shared-thanos-metrics
      endpoint: s3.us-east-1.amazonaws.com
      region: us-east-1
