apiVersion: v1
data:
  config: "apiVersion: kubeproxy.config.k8s.io/v1alpha1\nbindAddress: 0.0.0.0\nclientConnection:\n\
    \  acceptContentTypes: \"\"\n  burst: 10\n  contentType: application/vnd.kubernetes.protobuf\n\
    \  kubeconfig: /var/lib/kube-proxy/kubeconfig\n  qps: 5\nclusterCIDR: \"\"\nconfigSyncPeriod:\
    \ 15m0s\nconntrack:\n  maxPerCore: 32768\n  min: 131072\n  tcpCloseWaitTimeout:\
    \ 1h0m0s\n  tcpEstablishedTimeout: 24h0m0s\nenableProfiling: false\nhealthzBindAddress:\
    \ 0.0.0.0:10256\nhostnameOverride: \"\"\niptables:\n  masqueradeAll: false\n \
    \ masqueradeBit: 14\n  minSyncPeriod: 0s\n  syncPeriod: 30s\nipvs:\n  excludeCIDRs:\
    \ null\n  minSyncPeriod: 0s\n  scheduler: \"\"\n  syncPeriod: 30s\nkind: KubeProxyConfiguration\n\
    metricsBindAddress: 0.0.0.0:10249\nmode: \"iptables\"\nnodePortAddresses: null\n\
    oomScoreAdj: -998\nportRange: \"\""
kind: ConfigMap
metadata:
  labels:
    eks.amazonaws.com/component: kube-proxy
    k8s-app: kube-proxy
  name: kube-proxy-config
  namespace: kube-system
