apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrolebinding-eks-kube-proxy-windows.yaml
- clusterrolebinding-eks-kube-proxy.yaml
- configmap-kube-proxy-config.yaml
- configmap-kube-proxy.yaml
- daemonset-kube-proxy.yaml
- serviceaccount-kube-proxy.yaml
