# Role ARN for the KEDA operator service account. Regenerate: see docs/keda/README.md.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keda-irsa
  namespace: flux-system
spec:
  encryptedData:
    values.yaml: AgB77TCcxQydf3++TzTOgA4wBWK5nQcyCfGzcoZf7GnDx+EI7pU508rnJJ0ZvKEbSEqwVeWJUJYQuCrmHfv56NBXBaEzAntyOcAUiq2drGLFkJtZm9pl/iLcq2w6YfMcWs+YfxEWR4Yai/fMgzA5FvWrEaehVif54E/V36cISSvyhXmPZVSaBoA1tLlFqiT3fs5t5HzDDW60zgJtWZlJXuTIiy2pKdkZHBiTsQEnv/iQybkaMg1reBQZF6U8SWLiNerSndasZuDr4BteBhceDfslOiQroEIXLI/tZjWNmV4aUzpmy5PswVT+8ROblGmn0LZxD5f2ENrFuKw86IBxx3SYzIZDT3RPn+hhW7KCXqBKPKjKFIUh5SNHdM/ZVh8JY89ScnNIXQxN8U1433hVSBzn37ONaEGcmbFFlSn/VxrCt/R3KzWr5aiPUyAyvUMeIjSoLG/CGOwXLVrCuMabtypjFtMk1uyDwDuS1Mszg3iyXPjc4OisDyuWShpBK59U6U4i8I6qD6vv8AbCAmcrFR3+bYkLy2j7PP5VA9E7Q3ZhVLGs9vmj3KduZ7futI23Hgt9S/mJM0dyjdiTGmysrQeEqRc4LEtN9P4BcYh4pI2cyx3t2QQ6VX7afWTaVwlyUUY94pdLxvku8Cs+3bjJsf1c+v6wZsVRQXWuKVD6pry88XkqKW4ZmpbWX96iQO2eluumxpPYpX3sfBf5IOVuez5CotMz1iDu2J/DjGcSCzDBZrYc3c7iokC5ZgiCHesxIJ1xMItgKuvwak7j0+IdHOLNKQnhoAkrxEL0hqTmlakt/hVeAKceLb8Ije4eLB/9f4iS5ofWnbBV8PpnIYeS2g0dGWrdhStZLGq7oD/xINybQ/FHYQHQ1AOBgkS7g6QJMQ==
  template:
    metadata:
      name: keda-irsa
      namespace: flux-system
