apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-coredns.yaml
- deployment-coredns.yaml
- poddisruptionbudget-coredns.yaml
- service-kube-dns.yaml
- serviceaccount-coredns.yaml
