# gitops-flux/infrastructures/base/000-helm-repository
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - sealed-secrets.yaml
  - karpenter.yaml
  - istio.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - kiali.yaml
  - prometheus-community.yaml
  - eks-charts.yaml
  - aws-ebs-csi-driver.yaml
  - keda.yaml
  - teleport.yaml
  - kyverno.yaml
