---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluent-bit-es-credentials
  namespace: platform-logging
spec:
  encryptedData:
    password: AgAJR+MfGyIA9FgVmxOh0Dkx4t1OBBVTTo4DkwGJDQXYGN2ztBSDakB4PF0c/h1qHZWRv0MqrJOlkliBaS3K7Ry+aMu3yjYnFUwYczMPobQFXEwTRr3K8uL8dZpsQlGaBzfFvKtysln1V/A0AYkoZtp6TuhxbEdDB6gnqmUMwaHaJYx+CZlq3RXOJx0/NtaGKJEMKTPNvO1RSox7/DmLuAPxYFAB2XzTeVvZkc6jQyDTkkvNuaF6yfT5EfjCN8XVgdNYoJCahLlXm4zUE/Ahln3xuSJOP/E1w8Kqtd90kKSejbmobOEGi71iOWlxqMWUUSzMy/hEsEbm3VIcdK5YN8nBQ44GPz2qCVJE3hR2WnDG9DL2nc8cw2tsaz4SaD3T2QIwM4ThFtYn6h7zYZLJXxfavCu5NOh0kEvvtAQSQKaDIlL6RqQZLKwB3CtVTWtVx7ZAS+iapn3NH/lr3yn8vjfN42nvT0nTPxPv7BNSKigZ3HGs94GQlIzvxxwuPtBPo4BkYxTvKw5suYv+LabHpIwYcrl/tuoxlTZ5Mod4Lmm6xi3UtXUHIq53Low01ARBRY14Kqub2DvsKO+ZJ4+OONA4aCl93k1pnCYEgVlwaeE+P7w/ut+kpBliJkQV/bOzv3qTa4MSMmOhzU5o96rF24tN74fApwp0i3WTysZwpYYLeEYzVNTnsivRlBsUnVgOBT3m87ea17TL81cLvqSbkxXATi4oPOfuAe+UvRYB9DjFvg==
  template:
    metadata:
      name: fluent-bit-es-credentials
      namespace: platform-logging
